### ISSUE TITLE
"Download Status" icon missing in v2.5.0 ...

### ISSUE THREAD

**Issue by Vangelis66** [Lootyhoof/darkmoon#6]
Thanks anew for maintaining my preferred dark theme for the **Pale Moon** browser 🥇

**My specifics**:

OS: Windows 7 SP1 64-bit (Windows Aero _enabled_)
Browser: Pale Moon, 32-bit
Update channel: Unstable
appVersion: **29.0.0a6**
buildID: **20200827072427**
Complete Theme used: Dark Moon **2.5.0** (latest)

**Issue details**:

The `Download Status` icon is AWAL in latest version of DM 2.5.0: 

![DarkMoon-2 5 0](https://user-images.githubusercontent.com/9669492/91777078-8f30a200-ebf7-11ea-9f9e-16d23bc72ec6.jpg)

This button is associated with the `status-4-evar` code that is native to Pale Moon; the button **<ins>is</ins>** there when the default browser theme is used: 

![Default](https://user-images.githubusercontent.com/9669492/91777481-9efcb600-ebf8-11ea-9e0c-98042f35e618.jpg)

FWIW, previous version (**2.4.2**) of this complete theme does NOT manifest this bug: 

![DarkMoon-2 4 2](https://user-images.githubusercontent.com/9669492/91777594-ee42e680-ebf8-11ea-9440-1387e1adad21.jpg)

Hopefully, all this is just a simple omission, easy to mitigate... I'll stay myself at **2.4.2** until such time... 

Thanks in advance, most kind regards 😄

**Comment by Vangelis66** [comment]
UPDATE:
It would appear that https://github.com/Lootyhoof/darkmoon/commit/0dec084 (**Split statusbar styling per OS**) is the culprit... 

File `src/chrome/browser/statusbar/overlay.css` contained pre-commit the following CSS block: 
```css
#status4evar-download-button #status4evar-download-icon {
    min-width: 18px;
    min-height: 18px;
}
```
that was somehow _not_ transferred to the new "per OS" files... 😞 

I modified locally file `src/chrome/os/winnt/browser/statusbar/overlay.css` to read:

```css
/* Download status */

#status4evar-download-progress-bar {
   height: 4px;
}

#status4evar-download-button #status4evar-download-icon {
   min-width: 18px;
   min-height: 18px;
}

toolbar[mode="icons"] #status4evar-download-button[forcelabel="true"] > label {
   margin-inline-start: 5px !important;
}

/* Splitter */
```
... and that seems to have fixed it for me (on WinOS) 😄
